In [1]:
!python -n pip install numpy

Unknown option: -n
usage: python [option] ... [-c cmd | -m mod | file | -] [arg] ...
Try `python -h' for more information.


In [3]:
!python -m pip install numpy

     ---------------------------------------- 14.8/14.8 MB 1.1 MB/s eta 0:00:00


  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip available: 22.3.1 -> 23.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [4]:
import numpy

In [5]:
import keyword


In [6]:
keyword.iskeyword('if')

True

In [7]:
import keyword as kw

In [9]:
kw.kwlist

['False',
 'None',
 'True',
 'and',
 'as',
 'assert',
 'async',
 'await',
 'break',
 'class',
 'continue',
 'def',
 'del',
 'elif',
 'else',
 'except',
 'finally',
 'for',
 'from',
 'global',
 'if',
 'import',
 'in',
 'is',
 'lambda',
 'nonlocal',
 'not',
 'or',
 'pass',
 'raise',
 'return',
 'try',
 'while',
 'with',
 'yield']

In [11]:
from keyword import kwlist, iskeyword
kwlist

['False',
 'None',
 'True',
 'and',
 'as',
 'assert',
 'async',
 'await',
 'break',
 'class',
 'continue',
 'def',
 'del',
 'elif',
 'else',
 'except',
 'finally',
 'for',
 'from',
 'global',
 'if',
 'import',
 'in',
 'is',
 'lambda',
 'nonlocal',
 'not',
 'or',
 'pass',
 'raise',
 'return',
 'try',
 'while',
 'with',
 'yield']

In [12]:
iskeyword('int')

False

In [13]:
iskeyword('if')

True

In [14]:
iskeyword('for')

True

In [15]:
import numpy as np

In [16]:
a = np.array([])
a

array([], dtype=float64)

In [17]:
b = np.array([3,4,5,6,7])
b

array([3, 4, 5, 6, 7])

In [18]:
len(a)

0

In [19]:
len(b)

5

In [21]:
a.shape


(0,)

In [22]:
a.ndim

1

In [23]:
b.ndim

1

In [25]:
c = np.array([[2,3,4], [4,5,6], [6,7,8],[9,10,11]])
c

array([[ 2,  3,  4],
       [ 4,  5,  6],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [3]:
c

NameError: name 'c' is not defined

In [27]:
d = np.array([[[2,20], [3,20], [4,20]],
              [[4,40],[5,50], [6,60]],
              [[7,70], [8,80], [9,90]],
              [[3,34],[4,67], [6,78]]])
d

array([[[ 2, 20],
        [ 3, 20],
        [ 4, 20]],

       [[ 4, 40],
        [ 5, 50],
        [ 6, 60]],

       [[ 7, 70],
        [ 8, 80],
        [ 9, 90]],

       [[ 3, 34],
        [ 4, 67],
        [ 6, 78]]])

In [28]:
d.shape


(4, 3, 2)

In [29]:
c


array([[ 2,  3,  4],
       [ 4,  5,  6],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [30]:
c[0][1]

3

In [31]:
c[0:2,-1]

array([4, 6])

In [32]:
c[0:2,1:]

array([[3, 4],
       [5, 6]])