In [1]:
import numpy as np


In [2]:
!python -m pip install numpy


[notice] A new release of pip available: 22.3.1 -> 23.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
a = np.array([8,5,6])

In [4]:
a

array([8, 5, 6])

In [74]:
p = np.array([[3,8,4],
             [9,3,9],
             [11,15,17],
             [19,31,8]])

In [9]:
p.shape

(4, 3)

In [11]:
q = np.array([[[4,8,7],[3,1,5],[6,9,3]],
              [[41,81,71],[31,11,51],[61,91,131]]])

In [12]:
q.shape

(2, 3, 3)

In [13]:
q

array([[[  4,   8,   7],
        [  3,   1,   5],
        [  6,   9,   3]],

       [[ 41,  81,  71],
        [ 31,  11,  51],
        [ 61,  91, 131]]])

In [15]:
r = np.array([[[4,41],[8,81],[7,71]],
              [[3,31],[1,11],[5,51]],
              [[6,9],[9,91],[13,131]]])
r

array([[[  4,  41],
        [  8,  81],
        [  7,  71]],

       [[  3,  31],
        [  1,  11],
        [  5,  51]],

       [[  6,   9],
        [  9,  91],
        [ 13, 131]]])

In [16]:
r.shape


(3, 3, 2)

In [34]:
p[0:4:1,2]
#start:till:gap,column

array([ 4,  9, 17,  8])

In [46]:
p[3,0:3]  

array([19, 31,  8])

In [49]:
r[1:3,0:3]

array([[[  3,  31],
        [  1,  11],
        [  5,  51]],

       [[  6,   9],
        [  9,  91],
        [ 13, 131]]])

In [56]:
r[2:,0:,:1]

array([[[ 6],
        [ 9],
        [13]]])

In [57]:
r[1:,:1]

array([[[ 3, 31]],

       [[ 6,  9]]])

In [58]:
p+5
p

array([[ 3,  8,  4],
       [ 9,  3,  9],
       [11, 15, 17],
       [19, 31,  8]])

In [59]:
p=p+5
p

array([[ 8, 13,  9],
       [14,  8, 14],
       [16, 20, 22],
       [24, 36, 13]])

In [69]:
p[0] = p[0]+5
p[0]

array([ 8, 13,  9])

In [70]:
p[0,:] = p[0,:]-5


In [71]:
p[0,:]

array([3, 8, 4])

In [75]:
p[0:4:1,2]

array([ 4,  9, 17,  8])

In [76]:
p[0:4:1,2] = p[0:4:1,2]+2
p[0:4:1,2]

array([ 6, 11, 19, 10])

In [77]:
p

array([[ 3,  8,  6],
       [ 9,  3, 11],
       [11, 15, 19],
       [19, 31, 10]])

In [78]:
p[0:4:1,2]

array([ 6, 11, 19, 10])

In [79]:
p[0:4:1,2] = [1,2,3,4]
p

array([[ 3,  8,  1],
       [ 9,  3,  2],
       [11, 15,  3],
       [19, 31,  4]])

In [80]:
p[0:4:1,0] = [0,0,0,0]

In [81]:
p

array([[ 0,  8,  1],
       [ 0,  3,  2],
       [ 0, 15,  3],
       [ 0, 31,  4]])

In [82]:
p[:,1] = [9,8,7,6]

In [83]:
p

array([[0, 9, 1],
       [0, 8, 2],
       [0, 7, 3],
       [0, 6, 4]])

In [84]:
p[:2,1:] = [[101,201],[301,401]]
p

array([[  0, 101, 201],
       [  0, 301, 401],
       [  0,   7,   3],
       [  0,   6,   4]])

In [85]:
np.append(p,[[1,1,1]],axis = 0)

array([[  0, 101, 201],
       [  0, 301, 401],
       [  0,   7,   3],
       [  0,   6,   4],
       [  1,   1,   1]])

In [92]:
np.append(p,[[1],[2],[3],[3]],axis = 1)

array([[  0, 101, 201,   1],
       [  0, 301, 401,   2],
       [  0,   7,   3,   3],
       [  0,   6,   4,   3]])

In [94]:
p = np.append(p,[[1],[2],[3],[3]],axis = 1)

In [95]:
p

array([[  0, 101, 201,   1],
       [  0, 301, 401,   2],
       [  0,   7,   3,   3],
       [  0,   6,   4,   3]])

In [96]:
p = np.append(p,[[1,2,3,4]],axis = 0)
p

array([[  0, 101, 201,   1],
       [  0, 301, 401,   2],
       [  0,   7,   3,   3],
       [  0,   6,   4,   3],
       [  1,   2,   3,   4]])

In [98]:
np.delete(p,0,0)

array([[  0, 301, 401,   2],
       [  0,   7,   3,   3],
       [  0,   6,   4,   3],
       [  1,   2,   3,   4]])

In [99]:
p = np.delete(p,0,0)

In [100]:
p

array([[  0, 301, 401,   2],
       [  0,   7,   3,   3],
       [  0,   6,   4,   3],
       [  1,   2,   3,   4]])

In [103]:
np.delete(p,0,axis=1)

array([[301, 401,   2],
       [  7,   3,   3],
       [  6,   4,   3],
       [  2,   3,   4]])

In [104]:
p = np.delete(p,0,axis=1)

In [105]:
p

array([[301, 401,   2],
       [  7,   3,   3],
       [  6,   4,   3],
       [  2,   3,   4]])

In [106]:
p.reshape(6,2)

array([[301, 401],
       [  2,   7],
       [  3,   3],
       [  6,   4],
       [  3,   2],
       [  3,   4]])

In [107]:
p = p.reshape(6,2)

In [108]:
p


array([[301, 401],
       [  2,   7],
       [  3,   3],
       [  6,   4],
       [  3,   2],
       [  3,   4]])

In [110]:
a1 = np.array([3,4,5])
a1

array([3, 4, 5])

In [113]:
a1.dtype

dtype('int32')

In [114]:
a1.astype(float)

array([3., 4., 5.])

In [115]:
a1.__add__(12)

array([15, 16, 17])

In [116]:
a1.dtype

dtype('int32')

In [119]:
a1 = a1.astype(float)

In [120]:
a1.dtype

dtype('float64')

In [121]:
p.std(axis = 1)

array([50. ,  2.5,  0. ,  1. ,  0.5,  0.5])

In [122]:
p

array([[301, 401],
       [  2,   7],
       [  3,   3],
       [  6,   4],
       [  3,   2],
       [  3,   4]])

In [124]:
np.arange(1,11,1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [125]:
np.linspace(1,10,6)

array([ 1. ,  2.8,  4.6,  6.4,  8.2, 10. ])

In [126]:
np.random.randint(1.15,[3,4])

array([2, 3])

In [130]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [132]:
np.ones((2,3))


array([[1., 1., 1.],
       [1., 1., 1.]])

In [133]:
np.zeros((2,3),dtype=int)

array([[0, 0, 0],
       [0, 0, 0]])

In [134]:
np.dtype

numpy.dtype

In [137]:
np.arange(1,11,1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [138]:
np.linspace(1,10,10, dtype=int)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [139]:
list(range(1,11,2))

[1, 3, 5, 7, 9]

In [146]:
np.random.randint(1,6,1)


array([5])

In [151]:
np.random.randint(200,1666,[3,2])

array([[ 333,  473],
       [1292, 1643],
       [1116,  405]])

In [153]:
np.random.randint(200,300,[2,3])

array([[230, 230, 248],
       [267, 269, 295]])

In [ ]:
# nutsheel
# np.array()
# np.ones()
# np.zeros()
# np.arrange()
# np.linespace()
# np.random.randint()


In [4]:
import numpy as np

In [6]:
np.random.seed(54)
np.random.randint(31,6000,[4,3])

array([[ 929, 3886, 5174],
       [3840, 3423, 2096],
       [5160, 5669, 4744],
       [3350, 4835, 3347]])

In [7]:
np.random.rand(3,4)

array([[0.6714843 , 0.02965701, 0.39156203, 0.40479404],
       [0.18963101, 0.76710564, 0.61672315, 0.92627396],
       [0.32512403, 0.25315435, 0.72021792, 0.99695746]])

In [10]:
r = np.loadtxt('somedata.txt',dtype=str)

C:\Users\hp\AppData\Local\Temp\ipykernel_13564\1293489822.py:1: UserWarning: loadtxt: input contained no data: "somedata.txt"
  r = np.loadtxt('somedata.txt',dtype=str)


In [13]:
x = np.loadtxt('moredata.txt')
x

array([12., 23., 34.])

In [15]:
r = np.loadtxt('somedata.txt',dtype=str)
r

array(['this', 'is', 'my', 'file', 'outside', 'python'], dtype='<U7')

In [25]:
np.savetxt('new.txt',x,delimiter='   ')

In [22]:
np.savetxt('new1.txt',x,delimiter=',')